### ISSUE TITLE
Discriminator implementation?

### ISSUE THREAD

**Issue by kazimuth** [fperazzi/proSR#24]
Is the discriminator model going to be implemented at some point?

If not, I'm planning to implement it myself; I'd be happy to make a PR. I figure I can work from the [proSR supplement](http://igl.ethz.ch/projects/prosr/prosr-supplemental.pdf) and the `prosrgan.yaml` options file.

I'm curious what some of the discriminator options do, though:

```
D:
  act_params: {negative_slope: 0.2}
  act_type: LRELU
  input_residual: true
  ndf: 64
  scale_overhead: true
  update_freq: 2
  use_lsgan: true
  warmup_epochs: 0
  which_epoch: latest
  which_model_netD: srgan
```

In particular, I'm curious what `ndf`, `use_lsgan`, `scale_overhead`, and `input_residual` do. Do you know?
